### ISSUE TITLE
요청에 쿼리가 있는 경우 CGI mode로 진입하지 않음

### ISSUE THREAD

**Issue by yoouyeon** [Jay13Jeong/soo-je-webserver#44]
`GET /cgi-bin/form-get.py?intra_id=jeyoon&coalition=gam HTTP/1.1` 이런 요청에서 무한루프 돕니다.

**Comment by Jay13Jeong** [comment]
해결 완료!

**Comment by Jay13Jeong** [comment]
이제 GET도 화면은 뜨는데 무한로딩은 유지중....
