### ISSUE TITLE
conf 파일 정보 추가 여부 결정 필요 - cgi, upload_path

### ISSUE THREAD

**Issue by yoouyeon** [Jay13Jeong/soo-je-webserver#45]
현재는 location block 밖의 cgi 필드에서 cgi 설정 중. (location block 내의 cgi는 무시되는 중)

- Setup routes with one or multiple of the following rules/configuration (routes wont be using regexp):
  - Execute CGI based on certain file extension (for example .php). (cgi)
  - Make the route able to accept uploaded files and configure where they should be saved. (upload_path)

위 두가지를 location block 안에 추가할지, 다른 항목으로 대체할지 결정 필요

**Comment by Jay13Jeong** [comment]
첫번째는 cgi .py /usr/bin/python 형식으로 conf파일을 읽어서 처리할 예정입니다.
두번째는 PUT이가능한 location블록중에  root로 경로를 지정한것으로 대체 할 예정이긴합니다. (추가 논의가능)

**Comment by yoouyeon** [comment]
💡 **location 블록 내에 `cgi`, `client_max_body_size` 추가하기로 결정 (문법 규칙은 location block 밖과 동일)**

❗️아직 upload_path 는 결정 전입니다.

**Comment by Jay13Jeong** [comment]
업로드경로를 conf 파일의 로케이션블럭의 root로 업로드 하도록 결정
