### ISSUE TITLE
오토인덱스 디버깅 필요

### ISSUE THREAD

**Issue by Jay13Jeong** [Jay13Jeong/soo-je-webserver#59]
아직 해보지는 않았지만 오토인덱스 QA 필요합니다

**Comment by Jay13Jeong** [comment]
기본적으로 디폴트에러페이지, 오토인덱스 작동을 확인했지만, 다시한번 다같이 재확인  필요

**Comment by Jay13Jeong** [comment]
페이지 html링크를 빼던지 제대로 처리하던지 해야합니다.

**Comment by FeFe2200** [comment]
오토인덱스 하이퍼링크 태그에 클라이언트 uri경로(서버 경로X)를 추가하여 수정하였습니다

**Comment by Jay13Jeong** [comment]
철리님이 qa진행함.
