### ISSUE TITLE
POST - 없는 파일의 경우 -> status code 200/201

### ISSUE THREAD

**Issue by yoouyeon** [Jay13Jeong/soo-je-webserver#63]
**문제**
intra tester의 `POST http://localhost:8011/directory/youpla.bla` 의 수행 결과
현재는 404가 반환되었고 bad status code error가 남.

---

**해결 방향**
PUT과 동일하게 새로운 파일이 생성되어야 하고 201 Created 혹은 200 OK 를 반환해야 함.
(상태코드 의미상으로는 상태코드 201 이 맞는데 200 도 통과됨.)

**Comment by Jay13Jeong** [comment]
https://github.com/Jay13Jeong/soo-je-webserver/issues/72
