### ISSUE TITLE
POST multipart 에서 body가 따로 들어오는 문제

### ISSUE THREAD

**Issue by yoouyeon** [Jay13Jeong/soo-je-webserver#78]
간혹 `Content-Type : multipart/form-data` 인 경우에 body가 따로 들어옴.
원인 찾아 수정 필요함.

**Comment by Jay13Jeong** [comment]
이러면 또 리퀘스트를.......

**Comment by yoouyeon** [comment]
리퀘스트를.... 맞습니다...
multipart 의미 자체가 body를 여러 부분으로 나누어서 보내겠다는 뜻이었습니다...
Boundary 값으로 이 부분이 body의 시작임을 나타내고
Boundary 값 뒤에 하이픈 2개 (--) 가 붙은 값이 들어오기 전까지 계속해서 (?) 읽어줘야 하는 것 같습니다.
참고 : [https://brilliantdevelop.tistory.com/m/111](https://brilliantdevelop.tistory.com/m/111)
> 서버는 맨 처음 Content-type이 multipart/form-data;라는 걸 보고  boundary값을 통해 데이터가 나뉘어져 온다는 걸 인식하고 그에 맞게 해석하게 될 것이다.

**Comment by Jay13Jeong** [comment]
content length 체크해서 다시 받는걸로 해결 완료
