### ISSUE TITLE
config file 파싱 :예외처리부분 하기

### ISSUE THREAD

**Issue by FeFe2200** [Jay13Jeong/soo-je-webserver#86]
config file 파싱 :예외처리부분 하기
webserv.hpp에서

else 
    ;//예외처리하기

코드 넣기 hint : try{}catch(){}

**Comment by yoouyeon** [comment]
host의 값으로 127.0.0.1 외에도 형식만 맞다면 (`xxx.xxx.xxx.xxx`) 적용할 수 있게 한다. 😵
