### ISSUE TITLE
이제 더 이상 cgi처리에 waitpid는 필요없는 것으로 보임.

### ISSUE THREAD

**Issue by Jay13Jeong** [Jay13Jeong/soo-je-webserver#97]
출력이 많은 cgi처리시 fork부분에서  부모프로세스가 자식프로세스의 작업완료를 블락되어 기다리고있음.
waitpid함수를 제거하고 테스트해서 큰 이상이 안보이면 제거해도 괜찮을거 같음.

**Comment by Jay13Jeong** [comment]
waitpid제거시 대용량 cgi출력물 처리시 cgi의 출력 데이터를 보장하지 못함.

**Comment by yoouyeon** [comment]
`waitpid`의 세번째 인자로 `WNOHANG` 옵션을 주면 즉시 종료할 수 없을 때 기다리지 않고 0을 반환하기 때문에 반환값을 확인해서
- 정상종료(자식프로세스의 pid)
- 에러종료(-1)
- 보류(0)

여부를 알 수 있습니다.

이 값을 이용해서 정상종료가 아니면 계속 kqueue에 이벤트를 넣어서 `waitpid`를 계속하는 방식으로 CGI 블락을 해결해보려고 했고, 실제로도 블락 문제는 해결이 되었지만 (#105 참고)
에러종료 발생시에 무한응답이 발생하는 문제가 있어 일단은 되돌려 둔 상태입니다... 😩

**Comment by Jay13Jeong** [comment]
https://github.com/Jay13Jeong/soo-je-webserver/issues/106 에서 이슈완료했습니다
